version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: fintech_postgres
    environment:
      POSTGRES_USER: fintech
      POSTGRES_PASSWORD: fintech
      POSTGRES_DB: fintech_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/00_init.sql
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
volumes:
  pgdata:
